# version: '3.1'

services:
  suitecrm:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=suitecrm
      - DB_USER=admin
      - DB_PASSWORD=ngocnam2210

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ngocnam2210
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: admin
      MYSQL_PASSWORD: ngocnam2210
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
